name: Build e deploy

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

  setup-environment:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Configuração do ambiente
        run: |
          echo "Configurando o ambiente..."
          sleep 5

  build:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Compilação do código
        run: |
          echo "Compilando o código..."
          sleep 5

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execução dos testes
        run: |
          echo "Executando os testes..."
          sleep 5

  verify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Verificação dos testes
        run: |
          echo "Verificando os testes..."
          sleep 5

  generate-artifact:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Geração de artefato
        run: |
          echo "Gerando o artefato de build..."
          sleep 5

  deploy:
    runs-on: ubuntu-latest
    needs: generate-artifact
    steps:
      - name: Deploy e release
        run: |
          echo "Realizando deploy e release..."
          sleep 5

  success-notification:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notificação de sucesso
        run: |
          echo "Processo concluído com sucesso!"
          sleep 5
